/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/slider/slider.module';
import * as import2 from '@angular/common';
class Ng2ScrollSliderModuleInjector extends import0.ɵNgModuleInjector<import1.Ng2ScrollSliderModule> {
  _CommonModule_0:import2.CommonModule;
  _Ng2ScrollSliderModule_1:import1.Ng2ScrollSliderModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.Ng2ScrollSliderModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._Ng2ScrollSliderModule_1 = new import1.Ng2ScrollSliderModule();
    return this._Ng2ScrollSliderModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.Ng2ScrollSliderModule)) { return this._Ng2ScrollSliderModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Ng2ScrollSliderModuleNgFactory:import0.NgModuleFactory<import1.Ng2ScrollSliderModule> = new import0.NgModuleFactory<any>(Ng2ScrollSliderModuleInjector,import1.Ng2ScrollSliderModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RhcmVrL1Byb2plY3RzTWFjL25wbS9uZzItc2Nyb2xsLXNsaWRlci9zcmMvc2xpZGVyL3NsaWRlci5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZGFyZWsvUHJvamVjdHNNYWMvbnBtL25nMi1zY3JvbGwtc2xpZGVyL3NyYy9zbGlkZXIvc2xpZGVyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
